(dp1
S'output'
p2
S'<type \'exceptions.RuntimeError\'> Failure to connect, tried 5 times:\nTraceback (most recent call last):\n  File "/home/mdipierro/make_web2py/web2py/gluon/dal.py", line 7845, in __init__\n  File "/home/mdipierro/make_web2py/web2py/gluon/dal.py", line 688, in __call__\n  File "/home/mdipierro/make_web2py/web2py/gluon/dal.py", line 2728, in __init__\n  File "/home/mdipierro/make_web2py/web2py/gluon/dal.py", line 648, in reconnect\n  File "/home/mdipierro/make_web2py/web2py/gluon/dal.py", line 2726, in connector\n  File "/home/mdipierro/make_web2py/web2py/gluon/contrib/pymysql/__init__.py", line 93, in Connect\n  File "/home/mdipierro/make_web2py/web2py/gluon/contrib/pymysql/connections.py", line 575, in __init__\n  File "/home/mdipierro/make_web2py/web2py/gluon/contrib/pymysql/connections.py", line 741, in _connect\n  File "/home/mdipierro/make_web2py/web2py/gluon/contrib/pymysql/connections.py", line 796, in _request_authentication\n  File "/home/mdipierro/make_web2py/web2py/gluon/contrib/pymysql/connections.py", line 845, in _send_authentication\n  File "/home/mdipierro/make_web2py/web2py/gluon/contrib/pymysql/connections.py", line 341, in check_error\n  File "/home/mdipierro/make_web2py/web2py/gluon/contrib/pymysql/err.py", line 142, in raise_mysql_exception\n  File "/home/mdipierro/make_web2py/web2py/gluon/contrib/pymysql/err.py", line 135, in _check_mysql_exception\nOperationalError: (1045, u"Access denied for user \'root\'@\'localhost\' (using password: YES)")\n'
p3
sS'layer'
p4
S'C:\\Users\\Michael\\Desktop\\web2py\\applications\\PindarApp\\models\\db.py'
p5
sS'code'
p6
S"# -*- coding: utf-8 -*-\n\n#########################################################################\n## This scaffolding model makes your app work on Google App Engine too\n## File is released under public domain and you can use without limitations\n#########################################################################\n\n## if SSL/HTTPS is properly configured and you want all HTTP requests to\n## be redirected to HTTPS, uncomment the line below:\n# request.requires_https()\n\nif not request.env.web2py_runtime_gae:\n    ## if NOT running on Google App Engine use SQLite or other DB\n    db = DAL('sqlite://storage.sqlite',pool_size=1,check_reserved=['all'])\nelse:\n    ## connect to Google BigTable (optional 'google:datastore://namespace')\n    db = DAL('google:datastore')\n    ## store sessions and tickets there\n    session.connect(request, response, db=db)\n    ## or store session in Memcache, Redis, etc.\n    ## from gluon.contrib.memdb import MEMDB\n    ## from google.appengine.api.memcache import Client\n    ## session.connect(request, response, db = MEMDB(Client()))\n\n## by default give a view/generic.extension to all actions from localhost\n## none otherwise. a pattern can be 'controller/function.extension'\nresponse.generic_patterns = ['*'] if request.is_local else []\n## (optional) optimize handling of static files\n# response.optimize_css = 'concat,minify,inline'\n# response.optimize_js = 'concat,minify,inline'\n## (optional) static assets folder versioning\n# response.static_version = '0.0.0'\n#########################################################################\n## Here is sample code if you need for\n## - email capabilities\n## - authentication (registration, login, logout, ... )\n## - authorization (role based authorization)\n## - services (xml, csv, json, xmlrpc, jsonrpc, amf, rss)\n## - old style crud actions\n## (more options discussed in gluon/tools.py)\n#########################################################################\n\nfrom gluon.tools import Auth, Crud, Service, PluginManager, prettydate\nauth = Auth(db)\ncrud, service, plugins = Crud(db), Service(), PluginManager()\n\n## create all tables needed by auth if not custom tables\nauth.define_tables(username=False, signature=False)\n\n## configure email\nmail = auth.settings.mailer\nmail.settings.server = 'logging' or 'smtp.gmail.com:587'\nmail.settings.sender = 'you@gmail.com'\nmail.settings.login = 'username:password'\n\n## configure auth policy\nauth.settings.registration_requires_verification = False\nauth.settings.registration_requires_approval = False\nauth.settings.reset_password_requires_verification = True\n\n## if you need to use OpenID, Facebook, MySpace, Twitter, Linkedin, etc.\n## register with janrain.com, write your domain:api_key in private/janrain.key\nfrom gluon.contrib.login_methods.rpx_account import use_janrain\nuse_janrain(auth, filename='private/janrain.key')\n\n#########################################################################\n## Define your tables below (or better in another model file) for example\n##\n## >>> db.define_table('mytable',Field('myfield','string'))\n##\n## Fields can be 'string','text','password','integer','double','boolean'\n##       'date','time','datetime','blob','upload', 'reference TABLENAME'\n## There is an implicit 'id integer autoincrement' field\n## Consult manual for more options, validators, etc.\n##\n## More API examples for controllers:\n##\n## >>> db.mytable.insert(myfield='value')\n## >>> rows=db(db.mytable.myfield=='value').select(db.mytable.ALL)\n## >>> for row in rows: print row.id, row.myfield\n#########################################################################\ndb = DAL('mysql://root:Pindar2014@localhost/pindardb')\n\nfrom gluon.tools import *\nauth = Auth(db)\nauth.define_tables()\ncrud = Crud(db)\n\ndb.define_table('page',\n    Field('title'),\n    Field('body', 'text'),\n    Field('created_on', 'datetime', default=request.now),\n    Field('created_by', 'reference auth_user', default=auth.user_id),\n    format='%(title)s')\n\ndb.define_table('post',\n    Field('page_id', 'reference page'),\n    Field('body', 'text'),\n    Field('created_on', 'datetime', default=request.now),\n    Field('created_by', 'reference auth_user', default=auth.user_id))\n\ndb.define_table('document',\n    Field('page_id', 'reference page'),\n    Field('name'),\n    Field('file', 'upload'),\n    Field('created_on', 'datetime', default=request.now),\n    Field('created_by', 'reference auth_user', default=auth.user_id),\n    format='%(name)s')\n\ndb.page.title.requires = IS_NOT_IN_DB(db, 'page.title')\ndb.page.body.requires = IS_NOT_EMPTY()\ndb.page.created_by.readable = db.page.created_by.writable = False\ndb.page.created_on.readable = db.page.created_on.writable = False\n\ndb.post.body.requires = IS_NOT_EMPTY()\ndb.post.page_id.readable = db.post.page_id.writable = False\ndb.post.created_by.readable = db.post.created_by.writable = False\ndb.post.created_on.readable = db.post.created_on.writable = False\n\ndb.document.name.requires = IS_NOT_IN_DB(db, 'document.name')\ndb.document.page_id.readable = db.document.page_id.writable = False\ndb.document.created_by.readable = db.document.created_by.writable = False\ndb.document.created_on.readable = db.document.created_on.writable = False\n\n\n## after defining tables, uncomment below to enable auditing\n# auth.enable_record_versioning(db)\n"
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/mdipierro/make_web2py/web2py/gluon/restricted.py", line 220, in restricted\n  File "C:\\Users\\Michael\\Desktop\\web2py\\applications\\PindarApp\\models\\db.py", line 82, in <module>\n    db = DAL(\'mysql://root:Pindar2014@localhost/pindardb\')\n  File "/home/mdipierro/make_web2py/web2py/gluon/dal.py", line 7867, in __init__\nRuntimeError: Failure to connect, tried 5 times:\nTraceback (most recent call last):\n  File "/home/mdipierro/make_web2py/web2py/gluon/dal.py", line 7845, in __init__\n  File "/home/mdipierro/make_web2py/web2py/gluon/dal.py", line 688, in __call__\n  File "/home/mdipierro/make_web2py/web2py/gluon/dal.py", line 2728, in __init__\n  File "/home/mdipierro/make_web2py/web2py/gluon/dal.py", line 648, in reconnect\n  File "/home/mdipierro/make_web2py/web2py/gluon/dal.py", line 2726, in connector\n  File "/home/mdipierro/make_web2py/web2py/gluon/contrib/pymysql/__init__.py", line 93, in Connect\n  File "/home/mdipierro/make_web2py/web2py/gluon/contrib/pymysql/connections.py", line 575, in __init__\n  File "/home/mdipierro/make_web2py/web2py/gluon/contrib/pymysql/connections.py", line 741, in _connect\n  File "/home/mdipierro/make_web2py/web2py/gluon/contrib/pymysql/connections.py", line 796, in _request_authentication\n  File "/home/mdipierro/make_web2py/web2py/gluon/contrib/pymysql/connections.py", line 845, in _send_authentication\n  File "/home/mdipierro/make_web2py/web2py/gluon/contrib/pymysql/connections.py", line 341, in check_error\n  File "/home/mdipierro/make_web2py/web2py/gluon/contrib/pymysql/err.py", line 142, in raise_mysql_exception\n  File "/home/mdipierro/make_web2py/web2py/gluon/contrib/pymysql/err.py", line 135, in _check_mysql_exception\nOperationalError: (1045, u"Access denied for user \'root\'@\'localhost\' (using password: YES)")\n\n'
p11
s.